version: '3.9'

services:
    npm:
        image: node:20.9.0-slim
        container_name: app-dependecies
        working_dir: /globalbank_frontend
        volumes:
        - .:/globalbank_frontend
        command: npm install
        
    tests:
        image: node:20.9.0-slim
        container_name: app-test
        working_dir: /globalbank_frontend
        volumes:
        - .:/globalbank_frontend
        depends_on:
            npm:
                condition: service_completed_successfully
        command: npm run test

    app:
        image: node:20.9.0-slim
        container_name: app
        working_dir: /globalbank_frontend
        volumes:
        - .:/globalbank_frontend
        ports:
        - 4173:4173
        depends_on:
            npm:
                condition: service_completed_successfully
            tests:
                condition: service_completed_successfully
        command: npm run preview